version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR ...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k8t7n6p8
      - REPOSITORY_URI=public.ecr.aws/k8t7n6p8/my-python-app
      - IMAGE_TAG=user-app-latest
  build:
    commands:
      - echo Build started on 'date' ...
      - echo Building the user-app Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo Pushing the Docker image     
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"user-app-latest", "imageUri":"public.ecr.aws/k8t7n6p8/my-python-app:user-app-latest"}]' > imagedefinitions.json      
artifacts:
  files:
    - imagedefinitions.json
